import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import { ReactLenis } from "lenis/react";
import "./globals.css";

const font = Dosis({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={`${font.variable} antialiased`}>
                <ReactLenis root>{children}</ReactLenis>
            </body>
        </html>
    );
}
